// ═══════════════════════════════════════════════════════════════════════════
//  Image uploads.
//
//  Previously every route here was unauthenticated: anyone could write 10 MB
//  to disk, delete any stored image by name, and read storage statistics. The
//  content check trusted the client-declared mimetype, so an HTML or SVG
//  payload sent as image/png was accepted and then served from /uploads, which
//  is mounted ahead of the WAF.
//
//  Now: auth + rate limit on every route, magic-byte verification after the
//  write, an ownership record so one user cannot delete another's image, and
//  the public base URL comes from configuration instead of a hardcoded IP.
// ═══════════════════════════════════════════════════════════════════════════

const express = require('express')
const path = require('path')
const fs = require('fs/promises')

const router = express.Router()

const auth = require('../middleware/auth')
const { adminGuard } = require('../middleware/adminGuard')
const { imageUpload, IMAGE_DIR } = require('../middleware/uploads')
const { asyncHandler } = require('../utils/asyncHandler')
const logger = require('../utils/logger')
const v = require('../utils/validate')
const env = require('../config/env')
const { limiters } = require('../middleware/rateLimit')
const { detectImageType } = require('../utils/fileType')
const { BadRequestError, NotFoundError, ForbiddenError } = require('../utils/errors')
const File = require('../models/File')

// Stored filenames are generated by the upload middleware and always match this
// shape. Validating against it means a caller-supplied name can never reach the
// filesystem as anything else.
const STORED_NAME = /^img_[0-9]+_[a-f0-9]{8}\.(jpg|jpeg|png|gif|webp)$/

function publicUrlFor(filename) {
    const base = (env.PUBLIC_BASE_URL || '').replace(/\/+$/, '')
    // Relative URL when no base is configured: the frontend is served from the
    // same origin in every deployment, so this stays correct without pinning an
    // IP that drifts (the previous default disagreed with nginx's own config).
    return base ? `${base}/uploads/images/${filename}` : `/uploads/images/${filename}`
}

async function removeQuietly(filePath) {
    try { await fs.unlink(filePath) } catch { /* already gone */ }
}

// ─── POST /api/upload/image ─────────────────────────────────────────────────
router.post(
    '/api/upload/image',
    auth,
    limiters.heavy,
    imageUpload.single('image'),
    asyncHandler(async (req, res) => {
        if (!req.file) throw new BadRequestError('No image file provided', 'no_file')

        const filePath = path.join(IMAGE_DIR, req.file.filename)

        // Verify actual content, not the declared mimetype. multer's fileFilter
        // only sees the client's Content-Type header.
        const detected = await detectImageType(filePath)
        if (!detected) {
            await removeQuietly(filePath)
            throw new BadRequestError(
                'File content is not a supported image (jpg, png, gif, webp)',
                'invalid_image',
            )
        }

        await File.create({
            fileId: req.file.filename,
            userId: req.userId,
            filename: req.file.filename,
            contentType: detected.mime,
            size: req.file.size,
            path: `uploads/images/${req.file.filename}`,
        })

        logger.info('image.uploaded', {
            userId: req.userId,
            filename: req.file.filename,
            bytes: req.file.size,
            type: detected.mime,
        })

        res.json({
            url: publicUrlFor(req.file.filename),
            filename: req.file.filename,
            size: req.file.size,
            type: detected.mime,
            originalName: req.file.originalname,
        })
    }),
)

// ─── GET /api/upload/image/stats — admin only ───────────────────────────────
// Declared before the ':filename' route so the literal path is not captured by
// the parameter pattern.
router.get(
    '/api/upload/image/stats',
    auth,
    adminGuard,
    asyncHandler(async (_req, res) => {
        const [count, agg] = await Promise.all([
            File.countDocuments({ path: /^uploads\/images\// }),
            File.aggregate([
                { $match: { path: /^uploads\/images\// } },
                { $group: { _id: null, total: { $sum: '$size' } } },
            ]),
        ])
        const totalBytes = agg?.[0]?.total || 0
        res.json({
            count,
            totalSizeMB: (totalBytes / 1024 / 1024).toFixed(2),
        })
    }),
)

// ─── DELETE /api/upload/image/:filename ─────────────────────────────────────
router.delete(
    '/api/upload/image/:filename',
    auth,
    limiters.write,
    asyncHandler(async (req, res) => {
        const filename = v.str(req.params.filename, 'filename', { max: 128 })
        if (!STORED_NAME.test(filename)) {
            throw new BadRequestError('Invalid image filename', 'invalid_filename')
        }

        const record = await File.findOne({ fileId: filename })
        if (!record) throw new NotFoundError('Image not found', 'image_not_found')
        if (record.userId !== req.userId) {
            throw new ForbiddenError('You may only delete your own images', 'not_owner')
        }

        // basename() again as defence in depth even though the pattern above
        // already excludes separators.
        await removeQuietly(path.join(IMAGE_DIR, path.basename(filename)))
        await record.deleteOne()

        logger.info('image.deleted', { userId: req.userId, filename })
        res.json({ success: true })
    }),
)

module.exports = router
